src/dfs         : src/dfs.o src/functions.o src/mazeEnv.o
	gcc -I include/ -g -o src/dfs src/dfs.o src/functions.o src/mazeEnv.o -Wall

src/dfs.o       : src/dfs.c
	gcc -I include/ -g -o src/dfs.o -c src/dfs.c -Wall

src/functions.o : src/functions.c include/functions.h
	gcc -I include/ -g -o src/functions.o -c src/functions.c -Wall

src/mazeEnv.o   : src/mazeEnv.c include/mazeEnv.h
	gcc -I include/ -g -o src/mazeEnv.o -c src/mazeEnv.c -Wall

CC=gcc
CFLGAS=-Wall -Werror -I$(HOME)/Library/libin103-1.1/include
LDFLAGS=-L$(HOME)/Library/libin103-1.1/source -lin103 -lm

all: decision-tree.x

decision-tree.x: decision-tree.o utilio.o utilstr.o
	$(CC) $(CFLGAS) -o $@ $^ $(LDFLAGS)

%.o : %.c
	$(CC) $(CFLGAS) -c $<

clean:
	rm -f *~ *.o

realclean: clean
	rm -f *.x
